import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Santosh',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Shirt 1',
      slug: 'nike-slim-shirt-1',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Shirt 2',
      slug: 'nike-slim-shirt-2',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 130,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 12,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt 1',
      slug: 'adidas-fit-shirt-1',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 14,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt 2',
      slug: 'adidas-fit-shirt-2',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 110,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 18,
      description: 'high quality shirt',
    },
    {
      name: 'Puma Slim Shirt 1',
      slug: 'puma-slim-shirt-1',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 115,
      countInStock: 8,
      brand: 'Puma',
      rating: 4.2,
      numReviews: 9,
      description: 'high quality shirt',
    },
    {
      name: 'Puma Slim Shirt 2',
      slug: 'puma-slim-shirt-2',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 125,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 11,
      description: 'high quality shirt',
    },
    {
      name: 'Under Armour Shirt 1',
      slug: 'under-armour-shirt-1',
      category: 'Shirts',
      image: '/images/p7.jpg',
      price: 140,
      countInStock: 9,
      brand: 'Under Armour',
      rating: 4.6,
      numReviews: 13,
      description: 'high quality shirt',
    },
    {
      name: 'Under Armour Shirt 2',
      slug: 'under-armour-shirt-2',
      category: 'Shirts',
      image: '/images/p8.jpg',
      price: 135,
      countInStock: 7,
      brand: 'Under Armour',
      rating: 4.7,
      numReviews: 12,
      description: 'high quality shirt',
    },
    {
      name: 'Reebok Classic Shirt 1',
      slug: 'reebok-classic-shirt-1',
      category: 'Shirts',
      image: '/images/p9.jpg',
      price: 105,
      countInStock: 16,
      brand: 'Reebok',
      rating: 4.1,
      numReviews: 15,
      description: 'high quality shirt',
    },
    {
      name: 'Reebok Classic Shirt 2',
      slug: 'reebok-classic-shirt-2',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 95,
      countInStock: 11,
      brand: 'Reebok',
      rating: 4.0,
      numReviews: 13,
      description: 'high quality shirt',
    },
    {
      name: 'New Balance Shirt 1',
      slug: 'new-balance-shirt-1',
      category: 'Shirts',
      image: '/images/p11.jpg',
      price: 110,
      countInStock: 10,
      brand: 'New Balance',
      rating: 4.5,
      numReviews: 12,
      description: 'high quality shirt',
    },
    {
      name: 'New Balance Shirt 2',
      slug: 'new-balance-shirt-2',
      category: 'Shirts',
      image: '/images/p12.jpg',
      price: 115,
      countInStock: 9,
      brand: 'New Balance',
      rating: 4.4,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Asics Slim Shirt 1',
      slug: 'asics-slim-shirt-1',
      category: 'Shirts',
      image: '/images/p13.jpg',
      price: 125,
      countInStock: 13,
      brand: 'Asics',
      rating: 4.3,
      numReviews: 11,
      description: 'high quality shirt',
    },
    {
      name: 'Asics Slim Shirt 2',
      slug: 'asics-slim-shirt-2',
      category: 'Shirts',
      image: '/images/p14.jpg',
      price: 130,
      countInStock: 14,
      brand: 'Asics',
      rating: 4.5,
      numReviews: 12,
      description: 'high quality shirt',
    },
    {
      name: 'Champion Shirt 1',
      slug: 'champion-shirt-1',
      category: 'Shirts',
      image: '/images/p15.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Champion',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Champion Shirt 2',
      slug: 'champion-shirt-2',
      category: 'Shirts',
      image: '/images/p16.jpg',
      price: 95,
      countInStock: 18,
      brand: 'Champion',
      rating: 4.1,
      numReviews: 8,
      description: 'high quality shirt',
    },
    {
      name: 'Fila Slim Shirt 1',
      slug: 'fila-slim-shirt-1',
      category: 'Shirts',
      image: '/images/p17.jpg',
      price: 135,
      countInStock: 7,
      brand: 'Fila',
      rating: 4.4,
      numReviews: 12,
      description: 'high quality shirt',
    },
    {
      name: 'Fila Slim Shirt 2',
      slug: 'fila-slim-shirt-2',
      category: 'Shirts',
      image: '/images/p18.jpg',
      price: 140,
      countInStock: 6,
      brand: 'Fila',
      rating: 4.5,
      numReviews: 13,
      description: 'high quality shirt',
    },
    {
      name: 'Lululemon Shirt 1',
      slug: 'lululemon-shirt-1',
      category: 'Shirts',
      image: '/images/p19.jpg',
      price: 145,
      countInStock: 8,
      brand: 'Lululemon',
      rating: 4.6,
      numReviews: 14,
      description: 'high quality shirt',
    },
    {
      name: 'Lululemon Shirt 2',
      slug: 'lululemon-shirt-2',
      category: 'Shirts',
      image: '/images/p20.jpg',
      price: 150,
      countInStock: 5,
      brand: 'Lululemon',
      rating: 4.7,
      numReviews: 16,
      description: 'high quality shirt',
    },
    
  ],
};
export default data;
